-- Main Responsibility: Persist proposed receipt line items under an extraction.
--
-- One row per proposed line. Cascades when the parent document_extractions row
-- is deleted. category_id is optional (unknown slug stays null). Existing
-- Compose volumes do not re-run init scripts — apply this file once with psql
-- against the live database (see db/README.md).

BEGIN;

CREATE TABLE document_extraction_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extraction_id   BIGINT NOT NULL,
    description     VARCHAR(255) NOT NULL,
    amount          DECIMAL(12, 2) NOT NULL,
    category_id     BIGINT,
    position        INTEGER NOT NULL,
    CONSTRAINT document_extraction_lines_extraction_id_fk
        FOREIGN KEY (extraction_id) REFERENCES document_extractions (id) ON DELETE CASCADE,
    CONSTRAINT document_extraction_lines_category_id_fk
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT document_extraction_lines_amount_positive
        CHECK (amount > 0),
    CONSTRAINT document_extraction_lines_position_non_negative
        CHECK (position >= 0),
    CONSTRAINT document_extraction_lines_extraction_position_unique
        UNIQUE (extraction_id, position)
);

CREATE INDEX document_extraction_lines_extraction_id_idx
    ON document_extraction_lines (extraction_id);

COMMIT;
