-- Main Responsibility: Persist confirmed receipt lines under an expense.
--
-- Same shape as document_extraction_lines (description, optional quantity and
-- unit price, line total, optional category, position), owned by expenses.
-- Rows cascade when the expense is deleted (unapprove). category_id is
-- optional. Existing Compose volumes do not re-run init scripts — apply this
-- file once with psql against the live database (see db/README.md).

BEGIN;

CREATE TABLE expense_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      BIGINT NOT NULL,
    description     VARCHAR(255) NOT NULL,
    quantity        DECIMAL(12, 3),
    unit_price      DECIMAL(12, 2),
    amount          DECIMAL(12, 2) NOT NULL,
    category_id     BIGINT,
    position        INTEGER NOT NULL,
    CONSTRAINT expense_lines_expense_id_fk
        FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
    CONSTRAINT expense_lines_category_id_fk
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT expense_lines_amount_positive
        CHECK (amount > 0),
    CONSTRAINT expense_lines_quantity_positive
        CHECK (quantity IS NULL OR quantity > 0),
    CONSTRAINT expense_lines_unit_price_positive
        CHECK (unit_price IS NULL OR unit_price > 0),
    CONSTRAINT expense_lines_position_non_negative
        CHECK (position >= 0),
    CONSTRAINT expense_lines_expense_position_unique
        UNIQUE (expense_id, position)
);

CREATE INDEX expense_lines_expense_id_idx
    ON expense_lines (expense_id);

COMMIT;
